### PR TITLE
COMMERCE-4934 Dispatch Log Integration tests - after BC review

### PR DESCRIPTION
**Pull request by igorbeslic**
Please review

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:test:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:stop

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by vicnate5** [comment]
@igorbeslic Most recent test results show no unique failures. Please manually forward this to BChan and use "ci: reopen" (without the space)

**Comment by igorbeslic** [comment]
ci:reopen

**Pull request closed without merging**
